Expandable Team Cards + some other from feedback
bsefcic/sword-nation pull request #2
Opened 2022-07-25 14:30 UTC by saiyajinu

2022-07-25 14:51 UTC, bsefcic requested changes

2022-07-25 14:51 UTC, bsefcic commented on src/template/Home.tsx
> +      <div>home</div>
nu e ok aceasta componenta, ar trebui scoasa

2022-07-25 14:51 UTC, bsefcic commented on src/template/Base.tsx
> +    <Home />
scoate componenta neterminata

2022-07-25 14:51 UTC, bsefcic commented on src/pages/projects/sword-nation-chitila.tsx
> +import { Base } from '../../template/Base';
componenta incompleta, nu ar trebui sa ajunga in master

2022-07-25 14:51 UTC, bsefcic commented on src/project/Project.tsx
> +        <Link href={props.projectPath}>
e un link care nu duce nicaieri, scoate ce ai incercat cu proiectele si lasa pentru un alt branch si pull request

2022-07-25 14:51 UTC, bsefcic commented on src/template/Projects.tsx
> +      <Project projectPath="/" projectTitle="Proiectul Sports Nation - Pilot">
aceste linkuri nu functioneaza, scoate-le

2022-07-25 14:51 UTC, bsefcic commented on src/template/SupportUs.tsx
> +
nu ai de ce sa lasi o linie goala, sterge-o

2022-07-26 09:15 UTC, saiyajinu commented on src/template/SupportUs.tsx
> +
o face singur pluginu de curatat cod

2022-07-27 09:03 UTC, bsefcic approved these changes

2022-07-27 09:06 UTC, merged